spring:
  datasource:
    # h2는 MODE를 통해 Oracle, MySQL, PostgreSQL과 호환 가능
    url: jdbc:h2:tcp://localhost/~/datajpa;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace # sql 로그 기능. p6spy(외부 라이브러리)가 보기 더 편함